########################
# Device Setup
########################

substitutions:
  device_id: dog-house-temperature
  device_name: Dog House Temperature

esphome:
  name: "${device_id}"
  friendly_name: "${device_name}"

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

########################
# Software Stack Setup
########################

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Hotspot
    password: !secret wifi_fallback_password

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

########################
# Hardware Setup
########################

status_led:
  pin:
    number: GPIO2
    inverted: true

# I2C bus definition
i2c:
  scl: GPIO22
  sda: GPIO21
  scan: true

sensor:
  - platform: aht10
    variant: AHT20
    id: climate_sensor
    temperature:
      name: "Temperature"
      id: temperature_sensor
    humidity:
      name: "Humidity"
      id: humidity_sensor
    update_interval: 60s

  # Extra sensor to keep track of plug uptime
  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 2

  # Extra sensor for WiFi signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
