substitutions:
  device_id: pergola-relay-controller
  device_name: Pergola Relay Controller

esphome:
  name: "${device_id}"
  friendly_name: "${device_name}"

esp8266:
  board: esp01_1m

########################
# Software Stack Setup
########################

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - password: ""
    platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Hotspot
    password: !secret wifi_fallback_password

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

sensor:

  # Extra sensor to keep track of plug uptime
  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 2

  # Extra sensor for WiFi signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

########################
# Hardware Setup
########################

status_led:
  pin:
    number: GPIO13
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button 1"
    on_press:
      then:
        - switch.toggle: id_relay_1

  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "Button 2"
    on_press:
      then:
        - switch.toggle: id_relay_2

  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "Button 3"
    on_press:
      then:
        - switch.toggle: id_relay_3

  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Button 4"
    on_press:
      then:
        - switch.toggle: id_relay_4

  - platform: status
    name: "Status"

switch:
  - platform: gpio
    pin: GPIO12
    name: "Relay 1"
    id: id_relay_1

  - platform: gpio
    pin: GPIO5
    name: "Relay 2"
    id: id_relay_2

  - platform: gpio
    pin: GPIO4
    name: "Relay 3"
    id: id_relay_3

  - platform: gpio
    pin: GPIO15
    name: "Relay 4"
    id: id_relay_4
