########################
# Device Setup
########################

substitutions:
  device_id: plug-a
  device_name: Plug A

esphome:
  name: "${device_id}"
  friendly_name: "${device_name}"

esp8266:
  board: esp01_1m

########################
# Software Stack Setup
########################

# Enable logging
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)

# Enable Home Assistant API
api:
  reboot_timeout: 15min
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Hotspot
    password: !secret wifi_fallback_password

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"


########################
# Hardware Setup
########################

status_led:
  pin:
    number: GPIO13
    inverted: true

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:

  # Power measurement
  - platform: cse7766
    current:
      name: "Current"
      accuracy_decimals: 1
    voltage:
      name: "Voltage"
      accuracy_decimals: 1
    power:
      name: "Power"
      accuracy_decimals: 1
      id: power

  - platform: total_daily_energy
    name: "Daily Energy Consumption"
    power_id: power

  # Extra sensor to keep track of plug uptime
  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 2

  # Extra sensor for WiFi signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

binary_sensor:

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      then:
        - switch.toggle: relay

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

time:
  - platform: homeassistant
    id: timesrc
    on_time_sync:
      then:
        - logger.log: "Synchronized system clock"
