########################
# Device Setup
########################

substitutions:
  device_id: rfbridge-1
  device_name: RF Bridge 1

esphome:
  name: "${device_id}"
  friendly_name: "${device_name}"

esp32:
  board: esp32dev
  framework:
    type: arduino

########################
# Software Stack Setup
########################

# Enable logging
logger:

# Enable Home Assistant API
api:
  services:

  - service: send_code
    variables:
      code_str: string
    then:
    - remote_transmitter.transmit_pronto:
        data: !lambda 'return code_str;'

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Hotspot
    password: !secret wifi_fallback_password

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

sensor:

  # Extra sensor to keep track of plug uptime
  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 2

  # Extra sensor for WiFi signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

########################
# Hardware Setup
########################

# Enable board status LED
status_led:
  pin:
    number: GPIO2

remote_receiver:
  pin: GPIO26
  dump:
    - raw
  # Settings to optimize recognition of RF devices
  tolerance: 50%
  filter: 250us
  idle: 4ms

remote_transmitter:
  pin: GPIO27
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%
