########################
# Device Setup
########################

substitutions:
  device_id: garage
  device_name: Garage

  # RATGDO variables
  id_prefix: ${device_id}
  friendly_name: ${device_name}

  #1| OBS GPIO27
  #2| URX GPIO25
  #*********
  #3| UTX GPIO32
  #4| GND
  input_obst_pin: GPIO27
  uart_rx_pin: GPIO25
  uart_tx_pin: GPIO32

  # Output door status, HIGH for open (and closing), LOW for closed (and opening)
  # https://github.com/ratgdo/esphome-ratgdo/blob/05967a5cb1e27341e55917188c79ca80a610da5f/base.yaml#L248
  status_door_pin: GPIO21
  # Output obstruction status, HIGH for obstructed, LOW for clear
  status_obstruction_pin: GPIO22

  # Input for opening door
  # Pulled up input, set to LOW to start opening the door
  dry_contact_open_pin: GPIO17
  # Input for closing door
  # Pulled up input, set to LOW to start closing the door
  dry_contact_close_pin: GPIO18
  # Alternatively, set both to LOW at the same time to toggle:
  # https://github.com/ratgdo/esphome-ratgdo/blob/05967a5cb1e27341e55917188c79ca80a610da5f/base.yaml#L182

  # Input triggering light
  # Pulled up input, set to LOW to start closing the door
  dry_contact_light_pin: GPIO19

esphome:
  name: "${device_id}"
  friendly_name: "${device_name}"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

########################
# Software Stack Setup
########################

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Hotspot
    password: !secret wifi_fallback_password

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

sensor:

  # Extra sensor to keep track of plug uptime
  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 2

  # Extra sensor for WiFi signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

# RATGDO
packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

########################
# Hardware Setup
########################

status_led:
  pin:
    number: GPIO23
    inverted: true

binary_sensor:

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
     then:
       - switch.toggle: id_relay

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO16
    id: id_relay
    restore_mode: ALWAYS_OFF
