########################
# Device Setup
########################

substitutions:
  device_id: special-1
  device_name: Special 1

esphome:
  name: "${device_id}"
  friendly_name: "${device_name}"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

########################
# Software Stack Setup
########################

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Hotspot
    password: !secret wifi_fallback_password

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

sensor:

  # Extra sensor to keep track of plug uptime
  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 2

  # Extra sensor for WiFi signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

########################
# Hardware Setup
########################

status_led:
  pin:
    number: GPIO23
    inverted: true

binary_sensor:

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      then:
        - switch.toggle: id_relay

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO16
    id: id_relay
    restore_mode: ALWAYS_OFF
