########################
# Device Setup
########################

substitutions:
  device_id: light-a
  device_name: Light A

esphome:
  name: "${device_id}"
  friendly_name: "${device_name}"

esp8266:
  board: esp01_1m

########################
# Software Stack Setup
########################

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 15min
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Hotspot
    password: !secret wifi_fallback_password

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

sensor:
  # Extra sensor to keep track of plug uptime
  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 2

  # Extra sensor for WiFi signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

########################
# Hardware Setup
########################

status_led:
  pin:
    number: GPIO13
    inverted: true

binary_sensor:
  # Toggles the main relay on press of reset button
  - platform: gpio
    pin: GPIO00
    id: id_reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      then:
        - light.toggle:
            id: id_light

  # Toggles the main relay on switch toggle
  - platform: gpio
    pin: GPIO04
    id: id_switch
    internal: true
    on_press:
      then:
        - light.toggle:
            id: id_light
    on_release:
      then:
        - light.toggle:
            id: id_light

output:
  - platform: gpio
    pin: GPIO12
    id: id_relay

light:
  - platform: binary
    output: id_relay
    name: Light
    id: id_light
